try {
    throw "hello world";
} catch (e) {
    console.log("caught exception");
}
console.log("done");
